version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Maven"
      - yum install -y maven
  pre_build:
    commands:
      - echo "Caching Maven dependencies"
      - mvn dependency:go-offline
  build:
    commands:
      - echo "Building the project"
      - mvn package
  post_build:
    commands:
      - echo "Running tests"
      - mvn test
artifacts:
  files:
    - target/*.jar
  discard-paths: yes
