version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  # Specify Corretto 17 as the Java version
    commands:
      - echo "Installing JDK 17"
      - export JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto
      - export PATH=$JAVA_HOME/bin:$PATH
  pre_build:
    commands:
      - echo "Preparing build"
      - mvn clean
  build:
    commands:
      - echo "Building the project"
      - mvn install -DskipTests
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - target/*
