version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11  # Specify the Java runtime version if needed
  build:
    commands:
      - echo "Building the project"
      - mvn package
  post_build:
    commands:
      - echo "Running tests"
      - mvn test

artifacts:
  files:
    - target/*.jar  # Adjust according to your project's output artifacts

cache:
  paths:
    - /root/.m2/**/*  # Cache Maven dependencies to speed up subsequent builds
