version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11  # Use Amazon Corretto 11 as the JDK
    commands:
      - echo Installing Maven
      - yum install -y maven
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com)
      - echo Build started on date
  build:
    commands:
      - echo Building the Maven project...
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on date
      - echo Build artifacts location
artifacts:
  files:
    - target/*.jar
  discard-paths: yes
  base-directory: target
